#!/bin/sh


CURDIR=$(pwd)
export LD_LIBRARY_PATH=$CURDIR:$CURDIR/ffmpeg:/code/unix/libso/Linux:$CURDIR/lib:$CURDIR/qt:/usr/local/lib:$LD_LIBRARY_PATH
export PATH=$PATH:$CURDIR:$CURDIR/ffmpeg:$CURDIR/bin
export MALLOC_ARENA_MAX=1

chmod 777 ./gb28181
while [ 1 ]
do
    echo "wait for MySQL start"
    STATUS=$(tcptest 127.0.0.1:3306  5)
    if [ "$STATUS" == "OK" ]; then
        echo "MySQL started"
        ./gb28181  $1
        sleep 10
    else
        echo "MySQL not started, waitting"
        sleep 5
    fi
done
