#!/bin/sh


CURDIR=$(pwd)
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURDIR
export PATH=$PATH:$CURDIR


chmod 777 ./gb28181



while [ 1 ]
do
    echo "wait for MySQL start"
    STATUS=$(tcptest 127.0.0.1:3306  5)
    if [ "$STATUS" == "OK" ]; then
        echo "MySQL started"
        ./gb28181  $1
        sleep 10
    else
        echo "MySQL not started, waitting"
        sleep 5
    fi
done
