#!/bin/sh

ulimit -S -c unlimited
echo  "crash-%e-%s-%u-%g-%p-%t" > /proc/sys/kernel/core_pattern
sysctl  kernel.core_pattern="crash-%e-%s-%u-%g-%p-%t" 
# suffix of the core file name
echo  "1" > /proc/sys/kernel/core_uses_pid

CURDIR=$(pwd)
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CURDIR
export PATH=$PATH:$CURDIR
export MALLOC_ARENA_MAX=1

ulimit -n 50000
chmod 777 ./mediasrv


while [ 1 ]
do
    echo "wait for MySQL start"
    STATUS=$(tcptest 127.0.0.1:3306  5)
    if [ "$STATUS" == "OK" ]; then
        echo "MySQL started"
        ./mediasrv  $1
        sleep 10
    else
        echo "MySQL not started, waitting"
        sleep 5
    fi
done
